### ISSUE TITLE
" Error 0: Website ID must be set" when retrieving Customer Credit for a given customer

### ISSUE THREAD

**Issue by sebbrochet** [magecredit/magento-store-credit-rest-api#1]
When I use /customer/:customer_id/store_credit URL, I get an exception that says:
" Error 0: Website ID must be set"

Corresponding exception is raised by loadByCustomer method:
```PHP
public function loadByCustomer()
    {
        $this->_ensureCustomer();
        if ($this->hasWebsiteId()) {
            $websiteId = $this->getWebsiteId();
        } else {
            if (Mage::app()->getStore()->isAdmin()) {
                Mage::throwException(Mage::helper('wf_customerbalance')->__('Website ID must be set.'));
            }
            $websiteId = Mage::app()->getStore()->getWebsiteId();
        }
        $this->getResource()->loadByCustomerAndWebsiteIds($this, $this->getCustomerId(), $websiteId);
        return $this;
    }
```

Digging deeper, I see it fails on **$this->hasWebsiteId()** 

```php
public function hasWebsiteId()
    {
        Mage::log($this->getData());

        if (Mage::helper('wf_customerbalance')->isSharedBalanceEnabled()) {
            return true;
        }
        return parent::hasData('website_id');
    }
```

Please note, I'm not using **SharedBalance** between all my websites. In this case, code looks for a data with key 'website_id' that is not present.

If I dump my object, I can't see a top-level data with this key but website_id seems to be initialized inside the object:

```
(
    [customer_id] => 54
    [customer] => Mage_Customer_Model_Customer Object
        (
...
            [_data:protected] => Array
                (
                    [entity_id] => 54
                    [entity_type_id] => 1
                    [attribute_set_id] => 0
                    *****[website_id] => 6*****
                    [email] => xxxxxx@yyyyyy.com
                    [group_id] => 1
                    [increment_id] =>
                    [store_id] => 0
                    [created_at] => 2015-07-08T16:15:04+02:00
                    [updated_at] => 2015-07-08 14:15:04
                    [is_active] => 1
                    [disable_auto_group_change] => 0
                    [created_in] => Admin
                    [firstname] => aaaaa
                    [lastname] => bbbbb
                )
```

I can only assume code/tests have been designed with the **SharedBalance** ON but didn't work when it's OFF.

Let me know if you need more details.

Btw, thanks to have put the REST part on Github!

**Comment by jayelkaake** [comment]
Good catch Sebastian! 
I fixed the issue. I had to add 3 lines into both the V1.php files in the package.
Please update magecredit to 1.1.1.1 (which is the latest that will be downloaded when you use the link you were sent after the purchase).
As of Magecredit 1.1.1.1 you can provide a parameter ?website_id=*WEBSITE_ID* in your requests. I've also updated the readme in this repository to reflect.
